[package]
name = "bevy_voxel_world"
description = "A voxel world plugin for Bevy"
version = "0.3.2"
edition = "2021"
authors = ["Joacim Magnusson <joacim@isogram.se>"]
license = "MIT OR Apache-2.0"
homepage = "https://github.com/splashdust/bevy_voxel_world"
repository = "https://github.com/splashdust/bevy_voxel_world"
documentation = "https://github.com/splashdust/bevy_voxel_world"
readme = "README.md"
exclude = ["/assets/", "/examples/", "/.github/"]
keywords = ["bevy", "voxels", "gamedev", "voxelengine"]
categories = ["game-development", "graphics"]

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version = "0.12", features = [
    "bevy_render",
    "bevy_asset",
    "bevy_pbr",
] }
block-mesh = "0.2.0"
ndshape = "0.3.0"
futures-lite = "2.0.0"
rand = "0.8.5"
weak-table = { version = "0.3.2", features = ["ahash"] }

[dev-dependencies]
noise = "0.8.2"
